server.port=8081
spring.application.name=archix-base
spring.datasource.url=jdbc:postgresql://localhost:5432/archix-db
spring.datasource.username=postgres
spring.datasource.password=khalid123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=dff0d6d477a55fc7208a1095f8db44d66fb61af831cd5a4a22e1c02e20080b11
jwt.expiration=604800000

# File Upload Limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
